language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm test
  - npm run build
deploy:
  provider: npm
  skip_cleanup: true
  api_key: $NPM_API_KEY
  local_dir: build
  on:
    branch: master